[window]
  decorations = "none"
  opacity = 0.8
  dynamic_title = true
[window.dimensions]
  columns = 80
  lines = 20

[scrolling]
history = 5500
multiplier = 5
[font]
  size = 11
[font.bold]
  family = "victormono nerd font"
  style = "Bold"
[font.italic]
  family = "victormono nerd font"
  style = "Italic"
[font.bold_italic]
  family = "victormono nerd font"
  style = "Blod Italic"
[font.normal]
  family = "victormono nerd font"
  style = "Regular"

[cursor.style]
  shape = "Beam"
  blinking = "Never"

[selection]
  semantic_escape_chars= ",│`|:\"'' ()[]{}<>'"
  save_to_clipboard = true
[colors] # Catppuccin
  [colors.primary]
    background = "0x1E1D2F"
    foreground = "0xD9E0EE"
  [colors.cursor]
    text =   "0x1E1D2F"
    cursor = "0xF5E0DC"
  [colors.normal]
    black = "0x6E6C7E"
    red = "0xF28FAD"
    green = "0xABE9B3"
    yellow = "0xFAE3B0"
    blue = "0x96CDFB"
    magenta = "0xF5C2E7"
    cyan = "0x89DCEB"
    white = "0xD9E0EE"
  [colors.bright]
    black = "0x988BA2"
    red = "0xF28FAD"
    green = "0xABE9B3"
    yellow = "0xFAE3B0"
    blue = "0x96CDFB"
    magenta = "0xF5C2E7"
    cyan = "0x89DCEB"
    white = "0xD9E0EE"

